### ISSUE TITLE
`getSqlQueryResult` 유틸 함수에 대한 제안

### ISSUE THREAD

**Issue by autroshot** [hyemin12/book-store-project#23]
`getSqlQueryResult` 함수에 대해 몇 가지 의견 드립니다.

함수는 `connection`을 인자로 받아서 다시 반환하거나, `connection`을 만들어서 반환하고 있습니다. 제 생각으로는 `connection`을 반환하지 않는 것이 좋을 것 같습니다.
함수에서 `connection`을 반환하는 이유는 다른 쿼리에서 쓰기 위해서인 것 같습니다. 하지만 다른 쿼리에서 `connection`을 쓰고 싶다면, 함수에서 반환된 `connection`을 사용할 필요 없이 인자로 넣은 `connection`을 다시 사용하면 됩니다. 이미 [`ordersController`](https://github.com/hyemin12/book-store-project/blob/8223ab34e446977643c5bcda04c4301e5932060f/controller/ordersController.js#L43)에서 그렇게 하고 있습니다.
반환된 `connection`을 사용하는 곳이 `checkDataExistence` 함수 한 곳뿐이라는 것도 `connection` 반환이 크게 필요하지 않다는 걸 의미하기도 합니다.

[공식 문서](https://sidorares.github.io/node-mysql2/docs#using-connection-pools)에 의하면 `pool.query()`나 `pool.execute()`를 사용하면 매번 `release`를 할 필요 없다고 합니다. 쿼리가 끝나면 자동으로 릴리즈된다고 하니 참고 바랍니다. 주문과 같이 복수의 쿼리에서만, 이미 작성하신 것처럼 `connection`을 사용하고 `connection.release()`로 릴리즈하면 될 것 같습니다.

**Comment by hyemin12** [comment]
해당 내용 코드 수정 후 PR 완료 #24
