### ISSUE TITLE
불필요한 `??`

### ISSUE THREAD

**Issue by autroshot** [hyemin12/book-store-project#25]
[이곳](https://github.com/hyemin12/book-store-project/blob/557bb041c2f2d37c14e743b4230b48c0a24efbda/controller/booksController.js#L16C44-L16C44)에 다음과 같은 코드가 있습니다.

```js
const userId = req.user?.id ?? undefined;
```

`user`가 있는 경우와 없는 경우에 `userId`에 어떤 값이 할당되는지 정리하면 다음과 같습니다.

|                        | `req.user?.id`의 결과 | `req.user?.id ?? undefined`의 결과 |
| ---------------------- | --------------------- | ---------------------------------- |
| `user`가 존재          | `id`의 값             | `id`의 값                          |
| `user`가 존재하지 않음 | `undefined`           | `undefined`                        |

뒤의 `?? undefined`에 상관없이 결과가 동일한 것을 알 수 있습니다.

하지만 `id` 값이 `null`이라면 `req.user?.id`는 `null`,  `req.user?.id ?? undefined`는 `undefined`가 됩니다. 이를 의도하셨는지 모르겠지만 `id`에 `null`이 들어있는 것은 예외적인 상황 같습니다.

**Comment by hyemin12** [comment]
해당 코드 수정 후 PR 완료 #26
